### PR TITLE
Support for conflict target in on conflict update

### PR DESCRIPTION
**Pull request by mglonnro**

### CODE REVIEW

**Comment by davidkohn88** [comment]
Hi! Sorry I missed this, please request a review next time! Right now, I think there are some small merge conflicts if you can resolve that'd be great, I think it looks good though!

**Review by davidkohn88 — APPROVED** [review]
LGTM. Should work whether or not they're set, at some point we need to develop some tests for this function, but that requires a bit of infrastructure we don't currently have.

**Comment by davemsh** [comment]
Hi, could this PR be corrected and merged please? I've had to manually patch it in to fix the same issue I was experiencing.

**Review by davidkohn88 — APPROVED** [review]

**Comment by davidkohn88** [comment]
I think you need to rebase rather than merging master...

**Comment by mglonnro** [comment]
Somewhere down the road of rebasing, merging, etc, I got sincerely lost in the git jungle. So, I took the easy path out and made a new pull request over here: https://github.com/timescale/timescaledb-extras/pull/30

**Pull request closed without merging**
